"""Part families — a series answered once instead of per member.

Phase 7, ticket 07. `registry.py` owns membership (declared in
`registry/families.yaml`, proposed by `suggest.py`, never assumed), `build.py`
derives the index from records the members already publish (ADR 0005: quoted
cells, one pure function — the SI delta — and the printed row as the structural
label), and `render.py` writes `families/<NAME>/FAMILY_INDEX.md` under a hard
token budget. The corpus walk that feeds it lives in `retrieve/family.py`, where
every other corpus lookup lives.
"""

from datasheet_analyzer.families.build import (
    ALIGNED_FIELD,
    ALIGNED_PIN,
    ALIGNED_REGISTER,
    ALIGNED_ROW,
    ALIGNED_SECTION,
    ALIGNED_SECTION_TITLE,
    KIND_FIELD,
    KIND_PIN,
    KIND_REGISTER,
    KIND_SPEC,
    STATE_DIVERGENT,
    STATE_PARTIAL,
    STATE_SHARED,
    FamilyMember,
    MemberRecord,
    build_family_index,
    deltas_of,
    section_body,
)
from datasheet_analyzer.families.registry import (
    CANDIDATES_FILENAME,
    FAMILIES_FILENAME,
    FAMILIES_SCHEMA_VERSION,
    FamilyEntry,
    FamilyMiss,
    FamilyRegistry,
    FamilyUnconfirmed,
    candidates_path,
    candidates_yaml,
    families_path,
    families_yaml,
    is_candidate_path,
    load_candidates,
    load_families,
    miss_message,
    resolve,
    save_candidates,
    save_families,
    unconfirmed_message,
)
from datasheet_analyzer.families.render import (
    DELTA_HEADING,
    DIVERGENT_HEADING,
    FAMILY_INDEX_FILENAME,
    FAMILY_JSON_FILENAME,
    NOT_COMPARABLE_HEADING,
    PIN_HEADING,
    REGISTER_HEADING,
    SHARED_HEADING,
    banner,
    render_family_index,
)
from datasheet_analyzer.families.suggest import (
    MIN_SECTION_OVERLAP,
    MIN_STEM,
    PROPOSED_BY,
    CandidatePart,
    overlap,
    section_signature,
    stem,
    suggest_families,
)

__all__ = [
    "ALIGNED_FIELD",
    "ALIGNED_PIN",
    "ALIGNED_REGISTER",
    "ALIGNED_ROW",
    "ALIGNED_SECTION",
    "ALIGNED_SECTION_TITLE",
    "CANDIDATES_FILENAME",
    "DELTA_HEADING",
    "DIVERGENT_HEADING",
    "FAMILIES_FILENAME",
    "FAMILIES_SCHEMA_VERSION",
    "FAMILY_INDEX_FILENAME",
    "FAMILY_JSON_FILENAME",
    "KIND_FIELD",
    "KIND_PIN",
    "KIND_REGISTER",
    "KIND_SPEC",
    "MIN_SECTION_OVERLAP",
    "MIN_STEM",
    "NOT_COMPARABLE_HEADING",
    "PIN_HEADING",
    "PROPOSED_BY",
    "REGISTER_HEADING",
    "SHARED_HEADING",
    "STATE_DIVERGENT",
    "STATE_PARTIAL",
    "STATE_SHARED",
    "CandidatePart",
    "FamilyEntry",
    "FamilyMember",
    "FamilyMiss",
    "FamilyRegistry",
    "FamilyUnconfirmed",
    "MemberRecord",
    "banner",
    "build_family_index",
    "candidates_path",
    "candidates_yaml",
    "deltas_of",
    "families_path",
    "families_yaml",
    "is_candidate_path",
    "load_candidates",
    "load_families",
    "miss_message",
    "overlap",
    "render_family_index",
    "resolve",
    "save_candidates",
    "save_families",
    "section_body",
    "section_signature",
    "stem",
    "suggest_families",
    "unconfirmed_message",
]
